### ISSUE TITLE
Munki2 Clients not Inventorying

### ISSUE THREAD

**Issue by roudebusht** [munki/munkiwebadmin#26]
So far, I have setup the munkiwebadmin web server and repo. I have two MacOS clients pointed to the repo and confirmed that they are indeed pulling from it. I have pushed the 4 client scripts to both machines. Here is the problem I am having:

If I run "sudo /usr/local/munki/managedsoftwareupdate" :
This works correctly. Preflight, updates, postflight all run. The system inventories and shows up on the munkiwebadmin web server. No problems.

If I run "/Applications/Managed Software Center" GUI :
Updates run correctly. It tells me that preflight/postflight finish running, but the system never checks into the munkiwebadmin web server. There is no record of it on the web server.

This is a problem, because our end users will be using Managed Software Center rather than terminal commands. How can I get our MacOS clients to check in without using terminal commands?

Clients are at MacOS v10.10.5 and Managed Software Center v4.1.2531. munkiwebadmin is at newest version.

Thanks!

**Comment by gregneagle** [comment]
The preflight and postflight scripts do the MWA "checkin". If you are seeing the scripts run, then they are checking in.

I think you need to look a bit closer at what is going on. The log at /Library/Managed Installs/Log/ManagedSoftwareUpdate.log would be a good place to start.

Note that not every launch of Managed Software Center triggers a run of the /usr/local/munki/managedsoftwareupdate tool.

**Comment by gregneagle** [comment]
This is not a good place for general tech support -- I would suggest posting on the munki-discuss and/or the munki-web-admin list:

https://groups.google.com/group/munki-discuss
http://groups.google.com/group/munki-web-admin
